### PR TITLE
add "pyopenssl>=0.14"

### LINKED ISSUE #41: Synapse v0.23.1 won't start due to pyopenssl
It errors out with:
`Missing Requirement: Can't import 'OpenSSL' which is part of 'pyopenssl>=0.14' 
To install run: 
    pip install --upgrade --force "pyopenssl>=0.14"`

After running:  
`pip install --upgrade --force "pyopenssl>=0.14"  `
in the container it did start fine.

### PR DESCRIPTION
**Pull request by mvgorcum**
I think this should fix #41

### CODE REVIEW

**Comment by D4ndellion** [comment]
This didnt fix the issue for me

**Comment by mvgorcum** [comment]
Can you post the logs?

**Comment by D4ndellion** [comment]
Yeah sure
https://pomf.dodsorf.as/f/t0e8vh.txt
Same as before though

**Comment by mvgorcum** [comment]
Thanks for posting the logs.  
Yep this is not working. I forgot to escape the double quotes, which is why it did nothing, but also passed the build test.  
Unfortunately, when actually running `pip install --upgrade --force "pyopenssl>=0.14"` in the dockerfile the build fails because pip errors out with `RequirementParseError: Invalid requirement`

I'm confused as to why I am able to run the command in the container after it has been built, though.

**Pull request closed without merging**
