### PR TITLE
Remove Riot and separate turn and matrix

### PR DESCRIPTION
**Pull request by andreaspeters**
Hi Silvio,

my pull is a little bit messy, sorry for that. :-(
Well, my idea was, to deactivate riot, and separate matrix and turn. That means, I will start a container with the env "TURN=true", and it will only start the turn process. The same with matrix (MATRIX=true)! The reason is very easy, I dont want to have a container with three (riot, matrix and turn) different processes. Every one should have his own container. :-) 

Regards,
Andreas

### CODE REVIEW

**Comment by silvio** [comment]
Hi Andreas,

thanks for your contribution.
Can you make your PR more downward compatible. If I integrate your changes all upgraded and restarted containers runs with disabled turn and synapse. The administrator has to ensure to set TURN and MATRIX variables. It would be better not to introduce this behavior change.

Please change the variable names to something with DISABLE or ENABLE as pre or suffix.

**Comment by silvio** [comment]
... and please merge some commits together :-)

Thanks,
Silvio

**Comment by andreaspeters** [comment]
Hi Silvio,

no problem. :-) I will merge the current commits and change the variables to "TURN_DISABLE" and "MATRIX_DISABLE". And I will make it downward compatible therefore nobody will be in trouble. :-) 

Regards,
Andreas

**Comment by jbrinksmeier** [comment]
one question: will this be the new maintained repository for this project? https://github.com/AVENTER-UG/docker-matrix

**Comment by andreaspeters** [comment]
Just now we didnt got a answer from silvio. Actually we are a little bit worry about his situation. To keep docker-matrix up to date, we fork his latest version and start to maintain it. https://github.com/AVENTER-UG/docker-matrix

**Comment by andreaspeters** [comment]
I close this pull request. I will search a way to be more upward compatible.

**Pull request closed without merging**
