### PR TITLE
readme: point to synapse readme file

### LINKED ISSUE #36: Invalid network setup
You only expose port 8448 and recommend to change the self-signed certificate but it has been established in matrix-org/synapse#2438 that this is not the recommended setup.

Port 8448 and 8008 should be exposed, with a reverse proxy on 8008

### PR DESCRIPTION
**Pull request by silvio**
this fixes #36

Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

### CODE REVIEW

**Comment by andreaspeters** [comment]
Hi @silvio, is there a special reason why u dont merge your changes? :-)

**Comment by silvio** [comment]
I don't know. Looks okay to me ... :-)

**Comment by mvgorcum** [comment]
I'd argue that  this pull request should be merged now; it's fine.

However: we could endeavor to make a bit more of a detailed readme for the setup:  
The prevailing wisdom is that synapse should expose port 8448 with a self-signed certificate to use as the federation port, while port 8008 should be reverse proxied to port 443 with a valid cert (such as one from letsencrypt).

I guess the question is whether this readme should be sufficient to get the docker container up and running, without detailing how synapse should be configured, or whether the readme should try to help the average user to set up a working synapse server using the dockerfile.

**Comment by andreaspeters** [comment]
Well, I will not merge now, because I also changed the readme in my fork, together with some other changes. To prevent problems, I will add the readme changes to my fork and then merge it with these official repo. :-)

**Comment by andreaspeters** [comment]
I add it manualy. :-)

**Pull request closed without merging**
